version: 1.0.{build}
configuration:
- Debug
- Release
platform: x64
before_build:
- cmd: >-
    set PATH=C:\Qt\5.6\msvc2015_64\bin;%PATH%

    mkdir build

    cd build

    qmake -tp vc ../hdrv.pro "BOOST_ROOT=C:\Libraries\boost_1_60_0"

    cd ..
build:
  project: build\hdrv.vcxproj
  verbosity: minimal
after_build:
- cmd: 7z a hdrv_%CONFIGURATION%.zip %APPVEYOR_BUILD_FOLDER%\build\%CONFIGURATION%\hdrv.*
artifacts:
- path: hdrv_Debug.zip
  name: HDRV Debug
- path: hdrv_Release.zip
  name: HDRV Release
